name: build

on:
  workflow_run:
    workflows: ["lint"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.3
        id: build-app
        with:
          app-dir: fap
          sdk-channel: release

      - name: Rename artifacts
        run: for file in ${{ steps.build-app.outputs.fap-artifacts }}; do mv "$file" "${file%.*}-${{ steps.build-app.outputs.suffix }}.${file##*.}"; done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fap
          path: ${{ steps.build-app.outputs.fap-dir }}/*.fap
