name: lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ruff:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gui
    steps:
      - uses: actions/checkout@v4
      - name: Setup python3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: python -m pip install poetry~=1.8.0
      - run: poetry install
      - run: poetry run ruff check f0_usb_keyboard_bt_proxy
        env:
          FORCE_COLOR: 1

  mypy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gui
    steps:
      - uses: actions/checkout@v4
      - name: Setup python3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python -m pip install poetry~=1.8.0
      - run: poetry install
      - run: poetry run mypy
        env:
          FORCE_COLOR: 1
