name: publish

# on:
#   push:
#     tags:
#       - v*

on:
  push: []

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup python3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - run: python -m pip install poetry
      - run: poetry build
        working-directory: gui
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: gui/dist
